apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: microservices
type: Opaque
stringData:
  # admin / rabbitmq123
  rabbitmq-user: "admin"
  rabbitmq-password: "rabbitmq123"
  rabbitmq-erlang-cookie: "SUPERSECRETCOOKIE"
