{
 "title": "Microservices Overview",
 "tags": [ "microservices" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Scraped Targets (microservices)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(up{namespace=\"microservices\"}==1) or on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU secs/s by pod (microservices)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(process_cpu_seconds_total{namespace=\"microservices\"}[5m])) or sum by (pod) (rate(process_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "RSS Memory by pod (microservices)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (process_resident_memory_bytes{namespace=\"microservices\"}) or sum by (pod) (process_resident_memory_bytes)"
    }
   ]
  },
  {
   "title": "Samples scraped by job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (scrape_samples_post_metric_relabeling)"
    }
   ]
  }
 ]
}