apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
type: Opaque
stringData:
  # Change these before applying (dev defaults shown)
  admin-user: admin
  admin-password: password

# Usage:
# 1) Copy this file to grafana-secret.yaml and edit values
#    cp Manifests/monitoring/grafana-secret.example.yaml Manifests/monitoring/grafana-secret.yaml
# 2) Run: make monitoring
#    The Make target will apply the secret if present and restart Grafana.
