apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-bcfg
  namespace: microservices
spec:
  healthCheck:
    requestPath: /
    port: 3000
    type: HTTP
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
